export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE';
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSE';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';

export const LOADING_IMAGES = 'LOADING_IMAGES';
export const LOAD_IMAGES_SUCCESS = 'LOAD_IMAGES_SUCCESS';

export const LOADING_ALBUMS = 'LOADING_ALBUMS';
export const LOAD_ALBUMS_SUCCESS = 'LOAD_ALBUMS_SUCCESS';